syntax = "proto3";

package refb.merchant.v1;

option go_package = "refurbed/grpc/generated/merchant/v1";

// Numeric range filter is used for decimal numbers. It is especially
// used for monetary amounts and other quantities where exactness is required.
message NumericRangeFilter {
  optional string gt = 1; // Greater than.
  optional string ge = 2; // Greater than or equal to.
  repeated string any_of = 3;
  repeated string none_of = 4;
  optional string le = 5; // Less than or equal to.
  optional string lt = 6; // Less than.
}
