syntax = "proto3";

package refb.merchant.v1;

import "google/api/field_behavior.proto";
import "refb/descriptor.proto";
import "refb/merchant/v1/enums/sort_order.proto";
import "refb/merchant/v1/filters/bool_filter.proto";
import "refb/merchant/v1/filters/currency_code_filter.proto";
import "refb/merchant/v1/filters/market_type_filter.proto";
import "refb/merchant/v1/filters/string_filter.proto";
import "refb/merchant/v1/paginations/string_pagination.proto";
import "refb/merchant/v1/resources/market.proto";

option go_package = "refurbed/grpc/generated/merchant/v1";

// Service to retrieve information about markets.
service MarketService {
  // Lists all markets.
  //
  // Known errors:
  // - UNAUTHENTICATED
  //   - when no authorization header is sent
  //   - when authorization header is malformed or invalid
  // - PERMISSION_DENIED
  //   - when the authorized user does not have permissions for this operation
  // - INVALID_ARGUMENT
  //   - when pagination limit is too large (>100)
  //   - when both "ending_before" and "starting_after" are specified in pagination
  // - RESOURCE_EXHAUSTED
  //   - when rate limit is exceeded
  rpc ListMarkets(ListMarketsRequest) returns (ListMarketsResponse) {
    option (permission) = "merchant.market:list";
  }

  // Gets a single market.
  //
  // Known errors:
  // - UNAUTHENTICATED
  //   - when no authorization header is sent
  //   - when authorization header is malformed or invalid
  // - PERMISSION_DENIED
  //   - when the authorized user does not have permissions for this operation
  // - NOT_FOUND
  //   - when the market is not found
  // - RESOURCE_EXHAUSTED
  //   - when rate limit is exceeded
  rpc GetMarket(GetMarketRequest) returns (GetMarketResponse) {
    option (permission) = "merchant.market:view";
  }
}

message ListMarketsRequest {
  StringPagination pagination = 1;
  Sort sort = 2;
  Filter filter = 3;

  message Sort {
    SortOrderEnum.SortOrder order = 1;
    By by = 2;

    enum By {
      CODE = 0;
      NAME = 1;
    }
  }

  message Filter {
    StringFilter code = 1;
    BoolFilter is_site = 2;
    MarketTypeFilter type = 3;
    CurrencyCodeFilter currency = 4;
  }
}

message ListMarketsResponse {
  repeated Market markets = 1;

  // Indicates whether there are more results available.
  bool has_more = 2;
}

message GetMarketRequest {
  // The identifier of the market to get.
  string code = 1 [(google.api.field_behavior) = REQUIRED];
}

message GetMarketResponse {
  Market market = 1;
}
