syntax = "proto3";

package refb.merchant.v1;

import "google/api/field_behavior.proto";
import "google/api/resource.proto";
import "google/protobuf/timestamp.proto";
import "refb/merchant/v1/enums/battery_condition.proto";
import "refb/merchant/v1/enums/currency_code.proto";
import "refb/merchant/v1/enums/offer_grading.proto";
import "refb/merchant/v1/enums/offer_state.proto";
import "refb/merchant/v1/enums/offer_taxation.proto";
import "refb/merchant/v1/enums/offer_warranty.proto";
import "refb/merchant/v1/enums/rejection_category.proto";
import "refb/merchant/v1/resources/offer_market_price.proto";

option go_package = "refurbed/grpc/generated/merchant/v1";

// A merchant's offer.
message Offer {
  option (google.api.resource) = {type: "refb.merchant.v1/Offer"};

  // Primary key.
  int64 id = 1;

  // Version of this offer.
  int64 version = 2;

  // Indicates whether this is the currently available version.
  bool is_current = 3;

  // When the offer was initially created.
  google.protobuf.Timestamp created_at = 4;

  // The refurbed instance id ("product variant") this offer is for.
  int64 instance_id = 5;

  // Human-readable name of the instance this offer is for.
  string instance_name = 6;

  // The offer's state.
  OfferStateEnum.OfferState state = 7;

  // The merchant's SKU.
  //
  // Max. length is 256 unicode characters. SKUs cannot have leading or trailing
  // whitespace characters.
  //
  // Can be empty string for old offers that did not require SKU to be set.
  string sku = 8;

  // Grading of the item sold.
  OfferGradingEnum.OfferGrading grading = 9;

  // Warranty of the item sold.
  OfferWarrantyEnum.OfferWarranty warranty = 10;

  // The item's stock.
  uint32 stock = 11;

  // The shipping profile connected to this offer. This determines in what
  // markets the offer is sold and what the shipping costs are.
  int64 shipping_profile_id = 12;

  // Name of shipping profile.
  string shipping_profile_name = 13;

  // An optional secondary shipping profile id. Can be used to offer express
  // shipping next to standard shipping. Has to be different from the primary
  // shipping profile.
  optional int64 secondary_shipping_profile_id = 14;

  // Name of secondary shipping profile. Only returned if secondary shipping
  // profile is set.
  optional string secondary_shipping_profile_name = 15;

  // The taxation mode set for this offer.
  OfferTaxationEnum.OfferTaxation taxation = 16;

  // The taxation mode the offer uses. This is either the set offer taxation
  // or the global taxation mode (merchant account settings) that overrides it.
  OfferTaxationEnum.OfferTaxation real_taxation = 17;

  // Currency of reference prices.
  CurrencyCodeEnum.CurrencyCode reference_currency_code = 18;

  // Reference gross price of this offer. The reference price is used to
  // calculate prices of calculated offer market prices (the ones that haven't
  // been defined manually).
  string reference_price = 19;

  // Optional reference minimum price in market currency for automatic
  // repricing. The reference minimum price is used to calculate minimum prices
  // of calculated offer market prices (the ones that haven't been defined
  // manually).
  optional string reference_min_price = 20;

  // Configured market prices. Unique by market code.
  repeated OfferMarketPrice set_market_prices = 21 [(google.api.field_behavior) = UNORDERED_LIST];

  // Calculated market prices for all markets on which prices have not been
  // defined manually. Unique by market code.
  repeated OfferMarketPrice calculated_market_prices = 22 [(google.api.field_behavior) = UNORDERED_LIST];

  // The battery condition if set for the offer.
  optional BatteryConditionEnum.BatteryCondition battery_condition = 23;

  // The rejection reason set if offer was rejected.
  optional RejectionReason rejection_reason = 24;
}

message RejectionReason {
  string free_text = 1;
  RejectionCategoryEnum.RejectionCategory category = 2;
}
